name: patrickcoutinho
description: A new Flutter application.
version: 1.0.1+1

environment:
  sdk: ">=2.11.9 <3.0.0"

dependencies:
  animated_bottom_navigation_bar:
  flutter_svg:
  flutter:
    sdk: flutter
  dio:
  badges:
  cached_network_image:
  connectivity:
  cupertino_icons:
  dots_indicator:
  easy_localization: 2.3.3
  flutter_custom_tabs: 1.0.3
  flutter_html:
  flutter_icons:
  flutter_inappwebview:
  flutter_widget_from_html:
  google_fonts:
  google_sign_in:
  html:
  html_unescape:
  image_picker:
  intl: 0.17.0
  introduction_screen:
  launch_review:
  line_icons:
  lottie:
  md2_tab_indicator:
  package_info:
  path_provider:
  provider:
  share:
  shared_preferences:
  skeleton_text:
  toast:
  url_launcher:
  youtube_player_flutter:
  animated_progress_button:
  rounded_loading_button:
  firebase_analytics:
  font_awesome_flutter:
  ionicons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"




# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/news1.png
    - assets/news2.png
    - assets/news3.png
    - assets/news4.png
    - assets/news5.png
    - assets/news6.png
    - assets/news7.png
    - assets/splash.png
    - assets/done.json
    - assets/translations/
    - assets/images/svg/

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500

    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Light.otf
          weight: 400
        - asset: assets/fonts/Helvetica-Neue.otf
          weight: 500

    - family: Manrope
      fonts:
        # - asset: assets/fonts/Manrope-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
